[project]
name = "koyomi-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.1.0",
    "requests>=2.32.5",
    "skyfield>=1.53",
]
